config/routes.rb
Rails.application.routes.draw do
  # get 'appointments/index'
  # get 'appointments/new'

  root 'static_pages#index'

  resources :patients  

  resources :physicians do
    resources :appointments
  end

  resources :physicians do
    resources :articles
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :physician
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :physicians, through: :appointments
    

    # def self.search(search)
    # if params[:search]
    #     @patient = Patient.where('name LIKE ?', "%#{params[:search]}%")
    #   else
    #     @patient = Patient.all
    #   end
    # # end
end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments
    has_many :articles
    has_many :patients, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_physician
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index
    @appointments = Appointment.all
    # @patients = @patient.appointments.where(role: 'Patient')
    # @physicians = @physician.appointments.where(role: 'Physician')
  end

  def new
    @patients = Patient.all# - @physician.patients
    @appointment = @physician.appointments.new
    #@physician = Physician.all - @physician.patients
  end

  def create
    @appointment = @physician.appointments.new(appointment_params)
    if @appointment.save
      redirect_to physician_appointments_path(@physician)
    else
      render :new
    end
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to physician_appointments_path(@physician)
    else
      render :edit
    end
  end

def show
end

def edit
  @patients = Patient.all
  render :new
end

  def destroy
    @appointment.destroy
    redirect_to physician_appointments_path(@physician)
    # redirect_to root_path
  end

  private
  def set_physician
    @physician = Physician.find(params[:physician_id]) 
  end

  def set_appointment
    @appointment = @physician.appointments.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:date, :time, :role, :patient_id, :physician_id)
  end

  def datepicker_input form, field
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'YYYY-MM-DD'
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_physician
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @physicians = Physician.all
    @article = @physician.articles.new
  end

  def create
    @article = @physician.articles.new(article_params)
    if @article.save
      redirect_to physician_articles_path(@physician)
    else
      render :new
    end
  end

  def update
    @physicians = Physician.all
    if @article.update(article_params)
      redirect_to physician_articles_path(@physician)
    else
      render :new
    end
  end

def show
end

def edit
  render :new
end

  def destroy
    @article.destroy
    redirect_to physician_articles_path(@physician)
    # redirect_to root_path
  end

  private
  def set_physician
    @physician = Physician.find(params[:physician_id]) 
  end

  def set_article
    @article = @physician.articles.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :author, :physician_id)
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index

    if params[:search]
      @patient = Patient.where('name ILIKE ? OR age ILIKE ?',  "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @patient = Patient.all
    end
    # @patients = Patient.search(params[:search])
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
      if @patient.save
        redirect_to @patient
      else
        render :new
      end
  end

def edit
  render :new
end

def update
  if @patient.update(patient_params)
    redirect_to @patient
  else
    render :edit
  end
end

def destroy
  @patient.destroy
  redirect_to root_path
end

private
  def patient_params
    params.require(:patient).permit(:search, :name, :age, :phone_number, :reason)
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end

  

end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @physician = Physician.where('name ILIKE ? OR specialty ILIKE ?',  "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @physician = Physician.all
    end
  end

  def show
  end

  def new
    @physician = Physician.new
  end

  def create
    @physician = Physician.new(physician_params)
    if @physician.save
      redirect_to @physician
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @physician.update(physician_params)
      redirect_to @physician
    else
      render :new
    end
  end

  def destroy
    @physician.destroy
    redirect_to root_path
  end

  private
  def physician_params
    params.require(:physician).permit(:search ,:name, :specialty)
  end

  def set_physician
    @physician = Physician.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/appointments/index.html.erb
<h1 class="mb-3"><%= @physician.name %>'s Appointment Calendar</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
      <th scope="col">Reason</th>
      <th scope="col">Physician</th>
      <th scope="col">Date</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
      <% @physician.appointments.each do |appointment| %>
    <tr>
      <td><%= appointment.patient.name %></td>
      <td><%= appointment.patient.age %></td>
      <td><%= appointment.patient.reason %></td>
      <td><%= appointment.physician.name %></td>
      <td> <%= appointment.date %> - <%= appointment.time %></td>
      <td> <%= link_to 'Update Details', edit_physician_appointment_path(@physician, appointment) %> </td>
      <td> <%= link_to 'Remove', physician_appointment_path(@physician, appointment), method: :delete %> </td>
    </tr>
        <% end %>
  </tbody>
</table>

<hr>

<button class="btn btn-info"> 
 <%= link_to 'Back', physicians_path %>
</button>

<button class="btn btn-info"> 
<%= link_to 'New Appointment', new_physician_appointment_path(@physician) %>
</button>

app/views/appointments/new.html.erb
<h1>Add Appointment with <%= @physician.name %> </h1>

<div class="card card-form mb-3">
<div class="form-group">

<%= form_with(model: [@physician, @appointment], local: true ) do |f| %>

  <%= f.label :patient %>  <br />
  <%= f.select :patient_id, @patients.collect { |pa| [pa.name, pa.id] }, class: 'form-control form-control-lg' %>
  <br />
  <br />
  <%= f.label :date %>
<%= f.date_field :date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>

  <br />
  <%= f.label :time %>
  <%= f.time_field :time,
      value: "%H:%M",
      min: 'hh:mm:ss',
      max: 'hh:mm:ss', class: 'form-control'  %>
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>

<% end %>
</div>
</div>

<button>
 <%= link_to 'Cancel', physicians_path %>
</button>

app/views/articles/index.html.erb
<h1 class="mb-3"><%= @physician.name %>'s Articles</h1>

<hr>
<% @physician.articles.each do |article| %>
<h1><%= article.title %></h1>
<p><%= article.body %></p>
<p>Article by: <%= article.physician.name %></p>
<p> <%= link_to 'Update Details', edit_physician_article_path(@physician, article) %> - <%= link_to 'Remove', physician_article_path(@physician, article), method: :delete %> </p>
<% end %>

<hr>
<button class="btn btn-info"> 
<%= link_to 'New Article', new_physician_article_path(@physician) %>
</button>

app/views/articles/new.html.erb
<h1> New Health Article by: <%= @physician.name %> </h1>

<div class="card card-form mb-3">
<div class="form-group">

<%= form_for [@physician, @article] do |f| %>
<%= f.label :title %>
<%= f.text_field :title, required: true, class: 'form-control' %>
<br>
<%= f.label :body %>
<%= f.text_area :body, required: true, class: 'form-control' %>
<br>
<br>
<%= f.submit %>
<% end %>
</div>
</div>

<button>
 <%= link_to 'Cancel', physicians_path %>
</button>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
 <%= link_to root_path do %>
<i class="fas fa-user-md"></i>
<% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
         <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
     <%= link_to 'View Physicians', physicians_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
   <%= link_to 'View Patients', patients_path, class: 'nav-link' %>
      </li>
    </ul>
    <span class="navbar-text">
     <button class="btn btn-info">Login</button>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Office</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://kit.fontawesome.com/f7bc76f4fa.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
  <div class="container-fluid">
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/patients/index.html.erb
<h1>Patients</h1>

<hr />

<h2><%= @patient.length <= 0 ? "No patients" : "" %>  </h2> 

<div class="search mb-3">
<%= form_tag(patients_path,  method: :get) do %>
  <%= text_field_tag :search, params[:search], placeholder: 'Name or Age' %>
  <%= submit_tag 'Search', name: nil %> 
<% end %>
  <%= link_to 'Reset', patients_path %>

</div>

<ul>

  <% @patient.each do |patient| %>
    <li>
<div class="card card-form mb-3">
      <h1> Name: <%= link_to patient.name, patient %> </h1>
      <p> AGE: <%= patient.age %> • <%= patient.phone_number %> </p>
  <% end %>
    </li>
  </div>
</ul>

<center>
<button class="btn btn-info mt-3 mb-3"> 
<%= link_to 'Add patient', new_patient_path %>
</button>
</center>

app/views/patients/new.html.erb
<h1>Welcome to our practice</h1>
<h2>Please fill out the new patient form</h2>

<div class="card card-form mb-3">
<div class="form-group">

<%= form_for @patient do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, required: true, class: 'form-control' %>
    <br>
    <%= f.label :age %>
    <%= f.text_field :age, required: true, class: 'form-control' %>
    <br>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, required: true, class: 'form-control' %>
    <br>
    <%= f.label :reason %>
    <%= f.text_area :reason, required: true, class: 'form-control' %>
    <br>
    <%= f.submit %>
<% end %>

</div>
</div>

app/views/patients/show.html.erb
    <h1> Patient Name: <%= @patient.name %> </h1>
    <h2> Patient History</h2>
    <hr>
    <ul> 
    <li> Age: <%= @patient.age %>  </li>
    <li> Phone Number: <%= @patient.phone_number %>  </li>
    <li> Appointment Reason: <%= @patient.reason %> </li> 
    </ul>

<%= link_to 'New Appointment', new_physician_appointment_path(@patient, @physician) %>

<hr>

<p> Change patient status </p>

<button class="btn btn-info"> <%= link_to 'Back', root_path%> </button>

<button class="btn btn-warning"> <%= link_to 'Update Details', edit_patient_path(@patient) %> </button>

<button class="btn btn-danger">  <%= link_to 'Remove Patient', @patient,  method: :delete %> </button>

app/views/physicians/index.html.erb
<h1>Physicians</h1>
<hr />

<h2><%= @physician.length <= 0 ? "No patients" : "" %></h2> 

<div class="search mb-3">
<%= form_tag(physicians_path,  method: :get) do %>
  <%= text_field_tag :search, params[:search], placeholder: 'Last Name or Specialty' %>
  <%= submit_tag 'Search', name: nil %> 
<% end %>
  <%= link_to 'Reset', physicians_path %>

</div>

<ul>
  <% @physician.each do |physician| %>
    <li>

<div class="card card-form mb-3">
<div class="form-group">
      <h1><%= link_to physician.name, physician %></h1>
      <p>Specialty: <%= physician.specialty %></p>
      <p> <%= link_to 'See Appointments', physician_appointments_path(physician) %> </p>
      <p> <%= link_to 'See Articles', physician_articles_path(physician) %> </p>
</div>


</div>
    </li>
  <% end %>
</ul>

<center>
<button class="btn btn-info mt-3 mb-3"> 
<%= link_to 'New physician', new_physician_path %>
</button>
</center>

app/views/physicians/new.html.erb
<h1>Welcome to our practice</h1>
<h2>Please fill out the new physician form</h2>

<div class="card card-form mb-3">
<div class="form-group">

<%= form_for @physician do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, required: true, class: 'form-control' %>
    <br>
    <%= f.label :specialty %>
    <%= f.text_field :specialty, required: true, class: 'form-control' %>
    <br>
    <%= f.submit %>
<% end %>

</div>
</div>

app/views/physicians/show.html.erb
    <h1> Physician: <%= @physician.name %> </h1>
    <h2> Specialty Field: <%= @physician.specialty %> </h2>

    <ul> 
    <li>  </li> 
    </ul>
    
| <%= link_to 'See Appointments', [@physician, Appointment] %> |
<%= link_to 'New Appointment', new_physician_appointment_path(@physician) %> |
<%= link_to 'New Article', new_physician_article_path(@physician) %> |

<hr>


<p> Update physician details </p>

<button class="btn btn-info"> <%= link_to 'Back', physicians_path %> </button>

<button class="btn btn-warning"> <%= link_to 'Update Details', edit_physician_path(@physician) %> </button>

<button class="btn btn-danger">  <%= link_to 'Fire Physician', @physician,  method: :delete %> </button>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/index.html.erb
<h1>Welcome to the practice of Doctor Cascade</h1>
<p>How may I help you?</p>
<hr>
<p>I am a new patient & need to register</p>
<button class="btn btn-info mt-3 mb-3"> 
<%= link_to 'Patient Registration', new_patient_path %>
</button>
<hr>
<p>I am a new physician & need a job</p>
<button class="btn btn-info mt-3 mb-3"> 
<%= link_to 'Physician Application', new_physician_path %>
</button>